version: '3.8'

services:
  frontend:
    build: .
    container_name: angular_app
    ports:
      - "4200:4200"

    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start -- --host 0.0.0.0
